version: 2
jobs:
  build:
    working_directory: ~/eds-lessons-website
    branches:
      only:
        #- master # only run on master
    steps:
      - checkout
      - run:
          name: Get latest lesson commit
          working_directory: ~/eds-lessons-dev
          command: |
            # ACMRT -- only looks at changed files, not deleted ones
            changed_files=$(git diff-tree --no-commit-id --name-only --diff-filter=ACMRT -r HEAD 2>&1)
            # get names of changed files
            echo "${changed_files} ">> changed_files.txt
            # python scripts/parse_commit.py
    steps:
      - checkout
