version: 2
jobs:
  build:
    working_directory: ~/eds-lessons-website
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: "Set Python Version"
          command: pyenv global 3.7.0
      - run:
          name: Get latest lesson commit to master branch
          working_directory: ~/eds-lessons-website
          command: |
            # ACMRT -- only looks at changed files, not deleted ones
            changed_files=$(git diff-tree --no-commit-id --name-only --diff-filter=ACMRT -r -m HEAD 2>&1)
            # get names of changed files
            echo "${changed_files} ">> changed_files.txt
            # Remove unwanted files from commit and count files changed
            python scripts/parse-commit.py

            # Get latest commit message
            echo $(git log -1 --pretty=%B) > commit_msg_latest.txt
            if [[ -f website_files.txt ]]
            then
              echo "The following files were modified: "
              cat website_files.txt
            else
              echo "No files were modified in the last commit."
            fi
      - run:
          name: Get removed, renamed, or moved files
          working_directory: ~/eds-lessons-website
          command: |
            deleted_files=$(git diff-tree --no-commit-id --name-only --diff-filter=D -r HEAD 2>&1)
            # get names of changed files
            echo "${deleted_files} ">> deleted_files.txt
            python scripts/parse-deleted.py
            ls
      - run:
          name: Get & print current branch
          working_directory: ~/eds-lessons-website
          command: |
            # get the current branch
            echo $(git branch | sed -n -e 's/^\* \(.*\)/\1/p') > current_branch.txt
            # Print out current branch
            echo "Working on this branch: "
            cat current_branch.txt
      - run:
          name: Clone earthlab.github.io website branch NEW
          working_directory: ~/
          command: |
            chmod +x scripts/clone-io-repo.sh
            scripts/clone-io-repo.sh
      - run:
          name: Move Changed Files to earthlab.github.io
          working_directory: ~/eds-lessons-website
          command: |
            # Only Copy files to the live website repo if there are files to move
            if [[ -f website_files.txt ]]
            then
              echo "The following files were modified and will be updated on the io website: "
              cat website_files.txt
              python scripts/move-files.py
            else
              echo "There are no changes to push to the website repo."
            fi
      - run:
          name: Delete removed/renamed/moved images and posts from .io website
          working_directory: ~/eds-lessons-website
          command: |
            chmod +x scripts/delete-images-posts.sh
            scripts/delete-images-posts.sh
      - run:
          name: Push changes in files and images to earthlab.github.io repo
          working_directory: ~/earthlab.github.io
          command: |
            if [[ -f ~/eds-lessons-website/website_files.txt ]] || [ -f ~/eds-lessons-website/deleted_files.txt ]
            then
              # Be sure to see how many files there are and only commit if there are more than 0
              git status
              git config credential.helper 'cache --timeout=120'
              git config user.email "earth.lab@colorado.edu"
              git config user.name "Deployment Bot"
              OUTPUT=$( GIT_PAGER_IN_USE=true git status )
              echo "$OUTPUT"
              git add .
              # get current commit message
              commit_msg_latest=$(head -1 ~/eds-lessons-website/commit_msg_latest.txt)
              git commit --allow-empty -m "$commit_msg_latest"
              # Push quietly to prevent showing the token in log
              git push -q https://${EDS_LESSONS_GITHUB_TOKEN_EL}@github.com/earthlab/earthlab.github.io.git
            else
              echo "Nothing to commit as there were no changes"
            fi
